# Generated by Django 5.1.4 on 2025-06-04 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_chatroom_friendrequest_message_blocked_friends_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='chat_images/%Y/%m/%d/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('file_size', models.PositiveIntegerField(editable=False)),
                ('img_width', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('img_height', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.message')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
