# Generated by Django 5.1.4 on 2025-03-23 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_column_task_taskattachment_taskcomment_delete_note_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='column_ref',
        ),
    ]
